package modelo.scrabble;

public enum Evento {
	NUEVOS_JUGADORES,
	NUEVO_JUGADOR,
	JUGADOR_DESCONECTADO,
	NUEVA_PARTIDA,
	PARTIDA_CARGADA,
	PARTIDA_GUARDADA,
	NUEVA_PALABRA,
	CAMBIO_FICHAS,
	CAMBIO_ESTADO_PARTIDA
}
