package modelo.scrabble;

public enum Evento {
	
	NUEVO_JUGADOR,
	JUGADOR_DESCONECTADO,
	NUEVA_PARTIDA,
	PARTIDA_CARGADA,
	PARTIDA_GUARDADA,
	NUEVA_PALABRA,
	CAMBIO_FICHAS,
	CAMBIO_ESTADO_PARTIDA,
	FIN_PARTIDA,
	ERROR_ATRIL,
	ERROR_DICCIONARIO,
	ERROR_COORDENADAS,
	ERROR_VALIDACION_PALABRA,
	ERROR_DISPOSICION,
	
}
